name: pEp4iosIntern
options:
  bundleIdPrefix: software.pEp
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    SWIFT_VERSION: "5.0"
    CODE_SIGNING_ALLOWED: NO
targets:
  pEp4iosIntern:
    type: framework
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: software.pEp.pEp4iosIntern
        PRODUCT_MODULE_NAME: pEp4iosIntern
        DEFINES_MODULE: YES
